name: Srini Terraform deployment to AWS

on:
  push:
    branches:
      - development  # Triggers GitHub Actions when new files are pushed into the development branch

jobs:
  deploy:
    name: Deploy Terraform on AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # Change if needed

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Modify to your region

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra  # Change if needed

      - name: List Terraform Files After Init
        run: ls -Rla ./infra
        working-directory: ./infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./infra

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./infra

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./infra